type ROLE_ENERGY_BITCH = "EnergyBitch";
type ROLE_BOB_THE_BUILDER = "BobTheBuilder";

declare const ROLE_ENERGY_BITCH : ROLE_ENERGY_BITCH;
declare const ROLE_BOB_THE_BUILDER : ROLE_BOB_THE_BUILDER;

type ROLE = 
    | ROLE_ENERGY_BITCH 
    | ROLE_BOB_THE_BUILDER; 

type ACTION_HARVEST = "Harvest";
type ACTION_BUILD = "Build";
type ACTION_UPGRADE = "Upgrade";
type ACTION_NONE = "";

declare const ACTION_HARVEST : ACTION_HARVEST;
declare const ACTION_BUILD : ACTION_BUILD;
declare const ACTION_UPGRADE : ACTION_UPGRADE;
declare const ACTION_NONE : ACTION_NONE;

type ACTIONS =
    | ACTION_NONE
    | ACTION_HARVEST
    | ACTION_BUILD
    | ACTION_UPGRADE;